# Build a Docker image and scan it for issues using Veracode's Container Scan

trigger:
- none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'verademo.net'
  DOCKER_BUILDKIT: 1

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: 'Build and scan the docker image for verademo.net'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
# https://docs.veracode.com/r/veracode_sbom#target-type shows the different types of targets you can scan (i.e. image, repo, directory etc.)
# https://docs.veracode.com/r/veracode_sbom#flags shows the different formats you can use for container scanning
    - script: |
        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
        export VERACODE_API_KEY_ID=$(VERACODE_ID)
        export VERACODE_API_KEY_SECRET=$(VERACODE_KEY)
        ./veracode scan --type image --source $(imageName) --format table --output $(imageName)_table.txt
        ./veracode scan --type image --source $(imageName) --format json --output $(imageName)_json.json
        ./veracode scan --type image --source $(imageName) --format cyclonedx --output $(imageName)_cyclonedx.xml
      displayName: 'Download Veracode Container scan and scan image'
      continueOnError: true
      env:
        VERACODE_ID: $(VERACODE_ID)
        VERACODE_KEY: $(VERACODE_KEY)
    - publish: $(System.DefaultWorkingDirectory)/$(imageName)_table.txt
      artifact: Container_results_table
      displayName: 'Publish the table output'
    - publish: $(System.DefaultWorkingDirectory)/$(imageName)_json.json
      artifact: Container_results_json
      displayName: 'Publish the json output file'
    - publish: $(System.DefaultWorkingDirectory)/$(imageName)_cyclonedx.xml
      artifact: Container_results_cyclonedx
      displayName: 'Publish the cyclonedx output file'