# Build a Docker image and scan it for issues using Veracode's SCA

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'verademo.net'
  DOCKER_BUILDKIT: 1

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: 'Build and scan the docker image for verademo.net'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: |
          $(tag)
          latest
    - script: |
        curl -fsS https://tools.veracode.com/veracode-cli/install | sh
        ./veracode scan --type image --source $(imageName)
      displayName: 'Download Veracode SCA agent and scan image'
      env:
        VERACODE_ID: $(VERACODE_ID)
        VERACODE_KEY: $(VERACODE_KEY)
